2021-01-08 10:30:02,640 INFO    MainThread:9092 [internal.py:wandb_internal():62] W&B internal server running at pid: 9092
2021-01-08 10:30:02,641 DEBUG   HandlerThread:9092 [handler.py:handle_request():54] handle_request: check_version
2021-01-08 10:30:02,641 INFO    WriterThread:9092 [datastore.py:open_for_write():76] open: wandb/run-20210108_103002-3kbeay1a/run-3kbeay1a.wandb
2021-01-08 10:30:02,642 DEBUG   SenderThread:9092 [sender.py:send():89] send: header
2021-01-08 10:30:02,642 DEBUG   SenderThread:9092 [sender.py:send():89] send: request
2021-01-08 10:30:02,642 DEBUG   SenderThread:9092 [sender.py:send_request():98] send_request: check_version
2021-01-08 10:30:02,644 DEBUG   Thread-4  :9092 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): pypi.org:443
2021-01-08 10:30:02,730 DEBUG   Thread-4  :9092 [connectionpool.py:_make_request():433] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 52216
2021-01-08 10:30:02,762 DEBUG   SenderThread:9092 [sender.py:send():89] send: run
2021-01-08 10:30:02,765 DEBUG   SenderThread:9092 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/maxxxzdn/CompPsy/code, universal_newlines=False, shell=None, istream=<valid stream>)
2021-01-08 10:30:02,775 DEBUG   SenderThread:9092 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-08 10:30:03,034 WARNING MainThread:9092 [internal.py:wandb_internal():116] Internal process interrupt: 1
2021-01-08 10:30:03,080 DEBUG   SenderThread:9092 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-01-08 10:30:03,093 INFO    SenderThread:9092 [dir_watcher.py:__init__():167] watching files in: wandb/run-20210108_103002-3kbeay1a/files
2021-01-08 10:30:03,093 INFO    SenderThread:9092 [sender.py:_start_run_threads():486] run started: 3kbeay1a with start time 1610098202
2021-01-08 10:30:04,801 WARNING MainThread:9092 [internal.py:wandb_internal():116] Internal process interrupt: 2
2021-01-08 10:30:04,801 ERROR   MainThread:9092 [internal.py:wandb_internal():119] Internal process interrupted.
2021-01-08 10:30:05,094 INFO    SenderThread:9092 [sender.py:finish():608] shutting down sender
2021-01-08 10:30:05,094 INFO    SenderThread:9092 [dir_watcher.py:finish():280] shutting down directory watcher
2021-01-08 10:30:05,765 INFO    WriterThread:9092 [datastore.py:close():257] close: wandb/run-20210108_103002-3kbeay1a/run-3kbeay1a.wandb
2021-01-08 10:30:05,767 INFO    HandlerThread:9092 [handler.py:finish():267] shutting down handler
2021-01-08 10:30:06,095 INFO    SenderThread:9092 [dir_watcher.py:finish():309] scan: wandb/run-20210108_103002-3kbeay1a/files
2021-01-08 10:30:06,095 INFO    SenderThread:9092 [dir_watcher.py:finish():315] scan save: wandb/run-20210108_103002-3kbeay1a/files/config.yaml config.yaml
2021-01-08 10:30:06,096 INFO    SenderThread:9092 [file_pusher.py:finish():169] shutting down file pusher
2021-01-08 10:30:06,096 INFO    SenderThread:9092 [file_pusher.py:join():174] waiting for file pusher
2021-01-08 10:30:06,105 DEBUG   Thread-10 :9092 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-08 10:30:06,566 DEBUG   Thread-10 :9092 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-01-08 10:30:06,578 DEBUG   Thread-10 :9092 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): storage.googleapis.com:443
2021-01-08 10:30:06,984 DEBUG   Thread-10 :9092 [connectionpool.py:_make_request():433] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/aipp/eegcn/3kbeay1a/config.yaml?Expires=1610184606&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=g4DWCoVTgiHQIw6vynKsAE7Z9%2BdrAY%2FFz6%2BG4i82CpIdoorjPAQfc4tMkVwWu%2F9T67C0GlLn0uKETcfIIrwZsWhCPYwpm9Hh1gNztjTooXaUOQsYS%2FjYkvqpC9heeNV45n4tEcCi23jTNzOF2ZsG93jQ75kntfxUp4i5SPeMJ4HQb31Trj5iw06mMWltYMMvaKa9tT75BUlbZdqKmD7tCl4D0vcsCQVzpoSi%2Beuv133ANbUAoOn%2B5HIAdNK0mz4Q3Rcl3kzy0%2BbO6Phspqoge7nHi67vHUHCMa3g2J0yjJgdJGw%2FKbVHClb81oUjy2qHvS2N4n%2FFqKmg7VomOt%2BQbw%3D%3D HTTP/1.1" 200 0
2021-01-08 10:30:06,987 INFO    Thread-10 :9092 [upload_job.py:push():112] Uploaded file wandb/run-20210108_103002-3kbeay1a/files/config.yaml
2021-01-08 10:30:07,603 DEBUG   Thread-5  :9092 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-08 10:30:07,892 DEBUG   Thread-5  :9092 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /files/aipp/eegcn/3kbeay1a/file_stream HTTP/1.1" 200 None
2021-01-08 10:30:07,897 INFO    MainThread:9092 [internal.py:handle_exit():137] Internal process exited
