2021-01-08 10:28:34,592 INFO    MainThread:8896 [internal.py:wandb_internal():62] W&B internal server running at pid: 8896
2021-01-08 10:28:34,593 DEBUG   HandlerThread:8896 [handler.py:handle_request():54] handle_request: check_version
2021-01-08 10:28:34,593 INFO    WriterThread:8896 [datastore.py:open_for_write():76] open: wandb/run-20210108_102834-152vsd3r/run-152vsd3r.wandb
2021-01-08 10:28:34,594 DEBUG   SenderThread:8896 [sender.py:send():89] send: header
2021-01-08 10:28:34,594 DEBUG   SenderThread:8896 [sender.py:send():89] send: request
2021-01-08 10:28:34,594 DEBUG   SenderThread:8896 [sender.py:send_request():98] send_request: check_version
2021-01-08 10:28:34,596 DEBUG   Thread-4  :8896 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): pypi.org:443
2021-01-08 10:28:34,682 DEBUG   Thread-4  :8896 [connectionpool.py:_make_request():433] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 52216
2021-01-08 10:28:34,714 DEBUG   SenderThread:8896 [sender.py:send():89] send: run
2021-01-08 10:28:34,717 DEBUG   SenderThread:8896 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/maxxxzdn/CompPsy/code, universal_newlines=False, shell=None, istream=<valid stream>)
2021-01-08 10:28:34,728 DEBUG   SenderThread:8896 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-08 10:28:34,864 WARNING MainThread:8896 [internal.py:wandb_internal():116] Internal process interrupt: 1
2021-01-08 10:28:35,018 DEBUG   SenderThread:8896 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-01-08 10:28:35,031 INFO    SenderThread:8896 [dir_watcher.py:__init__():167] watching files in: wandb/run-20210108_102834-152vsd3r/files
2021-01-08 10:28:35,032 INFO    SenderThread:8896 [sender.py:_start_run_threads():486] run started: 152vsd3r with start time 1610098114
2021-01-08 10:28:47,591 WARNING MainThread:8896 [internal.py:wandb_internal():116] Internal process interrupt: 2
2021-01-08 10:28:47,592 ERROR   MainThread:8896 [internal.py:wandb_internal():119] Internal process interrupted.
2021-01-08 10:28:47,719 INFO    WriterThread:8896 [datastore.py:close():257] close: wandb/run-20210108_102834-152vsd3r/run-152vsd3r.wandb
2021-01-08 10:28:47,732 INFO    HandlerThread:8896 [handler.py:finish():267] shutting down handler
2021-01-08 10:28:48,036 INFO    SenderThread:8896 [sender.py:finish():608] shutting down sender
2021-01-08 10:28:48,036 INFO    SenderThread:8896 [dir_watcher.py:finish():280] shutting down directory watcher
2021-01-08 10:28:48,037 INFO    SenderThread:8896 [dir_watcher.py:finish():309] scan: wandb/run-20210108_102834-152vsd3r/files
2021-01-08 10:28:48,037 INFO    SenderThread:8896 [dir_watcher.py:finish():315] scan save: wandb/run-20210108_102834-152vsd3r/files/config.yaml config.yaml
2021-01-08 10:28:48,037 INFO    SenderThread:8896 [file_pusher.py:finish():169] shutting down file pusher
2021-01-08 10:28:48,037 INFO    SenderThread:8896 [file_pusher.py:join():174] waiting for file pusher
2021-01-08 10:28:48,042 DEBUG   Thread-10 :8896 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-08 10:28:48,330 DEBUG   Thread-10 :8896 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-01-08 10:28:48,340 DEBUG   Thread-10 :8896 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): storage.googleapis.com:443
2021-01-08 10:28:48,944 DEBUG   Thread-10 :8896 [connectionpool.py:_make_request():433] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/aipp/eegcn/152vsd3r/config.yaml?Expires=1610184528&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YtLnVue2uHpEzI8di9vzZrmvxosyb%2BZUpe13E%2Fyc96nSaHsdEKZoe7uaR%2BF8FWPbxt8kXB7SSVzvWWRxr7iQMv9fP2ZotAUkcBnUw84H9H%2B6NZ8Ovx0BeiA2BgxDji7pioQrbrBwIvvfiMGHvPEAtBjKv6b7Tj9fYSChCQ6h8Jt1sUrc%2BP4rSAbNECWkVIH5wkHCjmhFoM3gwbX0FI6QUsMAy0ChQvRhShfCXK%2Fl1xZx8C8hQk0yo0yaYFSIkUpcqhbsdmbLHQRGU87S%2FZaY7C6CkWB4dDNd%2BU1hOmIMkY9h32ZXzZnhGCywlHZEvDRKJkg491ht%2Bdp3XK1xhHJ8Uw%3D%3D HTTP/1.1" 200 0
2021-01-08 10:28:48,946 INFO    Thread-10 :8896 [upload_job.py:push():112] Uploaded file wandb/run-20210108_102834-152vsd3r/files/config.yaml
2021-01-08 10:28:49,544 DEBUG   Thread-5  :8896 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-08 10:28:49,792 DEBUG   Thread-5  :8896 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /files/aipp/eegcn/152vsd3r/file_stream HTTP/1.1" 200 None
2021-01-08 10:28:49,797 INFO    MainThread:8896 [internal.py:handle_exit():137] Internal process exited
