2021-01-08 10:29:53,318 INFO    MainThread:9046 [wandb_init.py:_log_setup():293] Logging user logs to wandb/run-20210108_102953-3oj5h06f/logs/debug.log
2021-01-08 10:29:53,318 INFO    MainThread:9046 [wandb_init.py:_log_setup():294] Logging internal logs to wandb/run-20210108_102953-3oj5h06f/logs/debug-internal.log
2021-01-08 10:29:53,318 INFO    MainThread:9046 [wandb_setup.py:_flush():69] setting env: {}
2021-01-08 10:29:53,318 INFO    MainThread:9046 [wandb_setup.py:_flush():69] setting user settings: {'email': 'maxxxzdn@gmail.com'}
2021-01-08 10:29:53,318 INFO    MainThread:9046 [wandb_setup.py:_flush():69] multiprocessing start_methods=fork,spawn,forkserver
2021-01-08 10:29:53,956 WARNING MainThread:9046 [wandb_init.py:init():492] interrupted
Traceback (most recent call last):
  File "/home/maxxxzdn/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 472, in init
    run = wi.init()
  File "/home/maxxxzdn/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 367, in init
    ret = backend.interface.communicate_check_version(
  File "/home/maxxxzdn/.local/lib/python3.8/site-packages/wandb/interface/interface.py", line 597, in communicate_check_version
    result = self._communicate(rec)
  File "/home/maxxxzdn/.local/lib/python3.8/site-packages/wandb/interface/interface.py", line 437, in _communicate
    return future.get(timeout)
  File "/home/maxxxzdn/.local/lib/python3.8/site-packages/wandb/interface/interface.py", line 58, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2021-01-08 10:29:53,961 INFO    MainThread:9046 [internal.py:handle_exit():137] Internal process exited
