2021-01-08 10:29:53,832 INFO    MainThread:9062 [internal.py:wandb_internal():62] W&B internal server running at pid: 9062
2021-01-08 10:29:53,834 DEBUG   HandlerThread:9062 [handler.py:handle_request():54] handle_request: check_version
2021-01-08 10:29:53,834 INFO    WriterThread:9062 [datastore.py:open_for_write():76] open: wandb/run-20210108_102953-3oj5h06f/run-3oj5h06f.wandb
2021-01-08 10:29:53,834 DEBUG   SenderThread:9062 [sender.py:send():89] send: header
2021-01-08 10:29:53,835 DEBUG   SenderThread:9062 [sender.py:send():89] send: request
2021-01-08 10:29:53,835 DEBUG   SenderThread:9062 [sender.py:send_request():98] send_request: check_version
2021-01-08 10:29:53,837 DEBUG   Thread-4  :9062 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): pypi.org:443
2021-01-08 10:29:53,935 DEBUG   Thread-4  :9062 [connectionpool.py:_make_request():433] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 52216
2021-01-08 10:29:53,956 WARNING MainThread:9062 [internal.py:wandb_internal():116] Internal process interrupt: 1
2021-01-08 10:29:54,714 WARNING MainThread:9062 [internal.py:wandb_internal():116] Internal process interrupt: 2
2021-01-08 10:29:54,714 ERROR   MainThread:9062 [internal.py:wandb_internal():119] Internal process interrupted.
2021-01-08 10:29:54,835 INFO    WriterThread:9062 [datastore.py:close():257] close: wandb/run-20210108_102953-3oj5h06f/run-3oj5h06f.wandb
2021-01-08 10:29:54,836 INFO    HandlerThread:9062 [handler.py:finish():267] shutting down handler
2021-01-08 10:29:54,965 INFO    SenderThread:9062 [sender.py:finish():608] shutting down sender
2021-01-08 10:29:54,966 INFO    MainThread:9062 [internal.py:handle_exit():137] Internal process exited
